apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns2

resources:
  - ns-istio-tenant-ns2.yaml
  - ../../../base


images:
  - name: ruby-ex-image
    newName: image-registry.openshift-image-registry.svc:5000/ns2/ruby-ex
    newTag: 'latest'

