apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: ns1

resources:
  - ns-istio-tenant-ns1.yaml
  - ns1-istio-gateway.yaml
  - ns1-istio-virtualserver.yaml
  - ../../../base

images:
  - name: sleep-image
    newName: tutum/curl
    newTag: 'latest'
  - name: ruby-ex-image
    newName: image-registry.openshift-image-registry.svc:5000/ns1/ruby-ex
    newTag: 'latest'

