apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns4

resources:
  - ns-istio-tenant-ns4.yaml
  - ../../../base

images:
  - name: ruby-ex-image
    newName: image-registry.openshift-image-registry.svc:5000/ns4/ruby-ex
    newTag: 'latest'

