apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ruby
  - sleep


images:
  - name: sleep-image
    newName: tutum/curl
    newTag: 'latest'


#  oc adm policy add-scc-to-user privileged -z default -n tutorial
