apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns3

resources:
  - ns-istio-tenant-ns3.yaml
  - ns3-istio-gateway.yaml
  - ns3-istio-virtualserver.yaml
  - ../../../base


images:
  - name: ruby-ex-image
    newName: image-registry.openshift-image-registry.svc:5000/ns3/ruby-ex
    newTag: 'latest'

